language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="melodic" ROS_REPO=ros UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="kinetic" CLANG_FORMAT_CHECK=file CLANG_FORMAT_VERSION=6.0

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
